#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.nourl"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.01d5ebd928c1e43d73c0220098fc767afafdcb80.name = "Upgrade from 5.44.0"
    #test_upgrade_from.d0549053f3de35b2b233a72a1ac7c5a28caa7f92.name = "Upgrade from 5.109.4~ynh1"
    test_upgrade_from.854c060c2f52ed3b9f917e6d822c5061ba17f9c3.name = "Upgrade from 5.130.6~ynh1 (latest v5)"
